### ISSUE TITLE
扫码登录不能使用

### ISSUE THREAD

**Issue by hgt803** [v7lin/fake_wechat#12]
```

I/MicroMsg.SDK.DiffDevOAuth(24554): start auth, appId = wx23*******6d03897
I/MicroMsg.SDK.GetQRCodeTask(24554): external storage available = false
D/NetworkSecurityConfig(24554): No Network Security Config specified, using platform default
D/MicroMsg.SDK.GetQRCodeTask(24554): doInBackground, url = https://open.weixin.qq.com/connect/sdk/qrconnect?appid=wx23f34add36d03897&noncestr=a23ca0e0b44b11e9b463dd78b3ac33fd&timestamp=1564657254899&scope=snsapi_userinfo&signature=0bc1f97357499e9dc1286e1dd418526d4b6faf8f, time consumed = 384(ms)
D/MicroMsg.SDK.GetQRCodeResult(24554): parse succ, save in memory, uuid = 011JUk--bFChAaUJ, appname = 自********卓, imgBufLength = 46157
D/MicroMsg.SDK.GetQRCodeTask(24554): onPostExecute, get qrcode success
D/MicroMsg.SDK.ListenerWrapper(24554): onAuthGotQrcode, qrcodeImgPath = null
D/AndroidRuntime(24554): Shutting down VM
E/AndroidRuntime(24554): FATAL EXCEPTION: main
E/AndroidRuntime(24554): Process: com.yaobao.ad, PID: 24554
E/AndroidRuntime(24554): java.lang.NullPointerException: Attempt to invoke interface method 'void com.tencent.mm.opensdk.diffdev.OAuthListener.onAuthGotQrcode(java.lang.String, byte[])' on a null object reference
E/AndroidRuntime(24554): 	at com.tencent.mm.opensdk.diffdev.a.b.onAuthGotQrcode(Unknown Source:49)
E/AndroidRuntime(24554): 	at com.tencent.mm.opensdk.diffdev.a.d.onPostExecute(Unknown Source:22)
E/AndroidRuntime(24554): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(24554): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(24554): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(24554): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24554): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(24554): 	at android.app.ActivityThread.main(ActivityThread.java:6847)
E/AndroidRuntime(24554): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24554): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(24554): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```

**Comment by v7lin** [comment]
微信sdk问题，今晚我看看

**Comment by hgt803** [comment]
@v7lin 好的，谢谢您，希望能尽快更新。您写的这个真的很好用！

**Comment by hgt803** [comment]
```
      WechatAccessTokenResp accessToken = await wechat.getAccessToken(appId: Config.wxAppID, appSecret: Config.wxAppSecret);
      WechatTicketResp sdkTicket = await wechat.getTicket(accessToken: accessToken.accessToken);
      wechat.startQrauth(appId: Config.wxAppID, scope: WechatScope.SNSAPI_USERINFO, ticket: sdkTicket.ticket);
```

**Comment by hgt803** [comment]
非常省事！

**Comment by v7lin** [comment]
升级 Android SDK 了，还没打 release，帮忙用以下方式引入验证一下吧
```
dependencies:
  fake_wechat:
    git:
      url: https://github.com/v7lin/fake_wechat.git
```

**Comment by hgt803** [comment]
好的！

**Comment by hgt803** [comment]
`pubspec.lock` : 
```
  fake_wechat:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: "391aac934270c26fa18f1a769c20feff5e0c3cda"
      url: "https://github.com/v7lin/fake_wechat.git"
    source: git
    version: "0.3.3"
```


run `flutter clean` 后 debug 还是老样子
