### ISSUE TITLE
添加了微信分享功能,appstore审核不通过

### ISSUE THREAD

**Issue by hoooou** [v7lin/fake_wechat#32]
只添加了微信分享功能,但是appstore审核说包含支付相关功能,上架失败,
我们检查发现有可能是sdk里面包含pay相关的代码,让他们检查出来了
大佬能不能更新一版只包含分享功能的包呀?

**Comment by v7lin** [comment]
ok

**Comment by v7lin** [comment]
没验证，先不发布到 pub.dev 上
有空帮忙验证一下
```
  wechat_kit: #^1.0.2
    git:
      url: https://github.com/v7lin/fake_wechat.git
      ref: ios
```
